[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.greenlet"
]

[phases.install]
cmds = [
  "cd backend && pip install --break-system-packages -r requirements/base.txt --no-binary greenlet"
]

[start]
cmd = "cd backend && python3 entrypoint.sh"
