"""
ORBITIQ-X v0.5.0 — Knowledge Corpus Expansion
===============================================
Phase 19: Expands from 185 → 500+ chunks.

New domains (4):
  propulsion          — rocket engines, thrusters, Isp, staging
  communications      — RF links, frequency, protocols, latency
  earth_observation   — sensors, resolutions, spectral bands, SAR
  commercial_space    — new space business models, SPAC, launch economics

Deepened domains (adding ~30 chunks each):
  orbital_mechanics, orbital_propagation, conjunction_analysis,
  debris_mitigation, satellite_constellations, space_environment,
  spacecraft_operations, ssa, standards_protocols, mission_planning

Sources: SMAD, Sutton Rocket Propulsion Elements, CCSDS standards,
  ESA Sentinel mission documents, NOAA publications, public domain.
"""

CORPUS_V5 = [

    # ─── PROPULSION (30 chunks) ──────────────────────────────────────────────

    {"id": "propulsion-rocket-eq-001", "domain": "propulsion",
     "title": "Tsiolkovsky Rocket Equation",
     "source": "Sutton, Rocket Propulsion Elements; Tsiolkovsky 1903",
     "text": "The Tsiolkovsky rocket equation Δv = Isp × g0 × ln(m0/mf) relates velocity change to specific impulse and mass ratio. m0 = initial mass (propellant + dry mass), mf = final dry mass, Isp = specific impulse in seconds, g0 = 9.80665 m/s². For a single-stage vehicle with Isp=450 s (LH2/LOX), mass ratio of 10 gives Δv=10,186 m/s. LEO requires ~9,300 m/s including gravity and drag losses (~1,500 m/s). This is why single-stage-to-orbit (SSTO) is extremely challenging. Staging improves performance by discarding empty tankage mass. Two-stage vehicles: Δv_total = Δv_1 + Δv_2 where each stage has its own mass ratio and Isp."},

    {"id": "propulsion-isp-001", "domain": "propulsion",
     "title": "Specific Impulse by Propellant Combination",
     "source": "Sutton, Rocket Propulsion Elements 8th ed.",
     "text": "Specific impulse (Isp) measures propellant efficiency (seconds). Vacuum Isp by propellant: LOX/LH2 (Space Shuttle SSME): 453 s — highest of common chemical propellants; LOX/RP-1 (Falcon 9 Merlin 1D): 311 s SL, 348 s vac; LOX/LCH4 (SpaceX Raptor): 350 s SL, 380 s vac; N2O4/UDMH (Soviet engines, Proton): 315 s; Hydrazine monoprop: 220-230 s; Solid APCP (SRBs): 250-280 s; Arcjet (electric): 500-1000 s; Hall thruster: 1500-3000 s; Ion thruster (Dawn NEXT): 3100 s. Trade: high Isp chemical propellants (LH2) have very low density (71 kg/m³), requiring large, heavy tanks. Dense propellants (RP-1: 820 kg/m³) have lower Isp but smaller tankage."},

    {"id": "propulsion-merlin-001", "domain": "propulsion",
     "title": "SpaceX Merlin Engine Family",
     "source": "SpaceX technical documentation; press kits",
     "text": "SpaceX Merlin 1D (Falcon 9): oxidizer-rich staged combustion cycle, LOX/RP-1. Sea-level: 845 kN thrust, 282 s Isp. Vacuum: 934 kN thrust, 348 s Isp. Mass: 470 kg (engine + actuators). Throttle: 40-100%. T/W ratio: ~180:1 (one of highest in operational liquid engines). Nine Merlin engines on Falcon 9 first stage produce 7,607 kN total liftoff thrust. Engine-out capability: mission continues with any one engine out. Merlin Vacuum (upper stage): fixed nozzle, 1 MN thrust in vacuum. Turbopump: single-shaft, runs on turbine gas from preburner. Merlin development history: derived from Fastrac engine program, first flown 2006 (Falcon 1), continually upgraded to 1D+ variant with 10% thrust uprate."},

    {"id": "propulsion-raptor-001", "domain": "propulsion",
     "title": "SpaceX Raptor Engine — Full-Flow Staged Combustion",
     "source": "SpaceX technical presentations; Musk tweets; public data",
     "text": "Raptor is a full-flow staged combustion (FFSC) LOX/LCH4 engine — only the second FFSC engine to fly (after Soviet RD-270 prototype). FFSC burns all propellant through both preburners, maximizing cycle efficiency. Raptor 2 specifications: 230 bar chamber pressure (highest of any flight engine), 2 MN thrust, 350 s SL Isp, 380 s vac Isp, 1,600 kg mass. Raptor Vacuum: larger nozzle, 258 bar, 230 kN more thrust in vacuum. 33 Raptors on Starship superheavy booster (74.4 MN total), 6 Raptors on Starship upper stage. Key advantage: methane allows full reusability (no coking), Martian ISRU production is theoretically possible (Sabatier process: CO2 + H2 → CH4 + H2O)."},

    {"id": "propulsion-hall-thruster-001", "domain": "propulsion",
     "title": "Hall Effect Thruster Technology",
     "source": "Goebel & Katz, Fundamentals of Electric Propulsion; NASA Glenn",
     "text": "Hall effect thrusters (HET) use crossed electric and magnetic fields to ionize and accelerate xenon propellant. Operation: electrons are trapped in annular Hall drift by radial magnetic field; electrons ionize xenon propellant; electric field accelerates ions to exhaust velocities of 15,000-30,000 m/s. Specific impulse: 1,500-3,000 s. Thrust: 5-1000 mN (scales with power). Power/thrust: ~60 mW/mN. Applications: GEO station-keeping (Boeing 702 all-electric: 4× XIPS-25), MEO (EUTELSAT 115 West B), LEO constellation disposal. All-electric GEO orbit raising: saves 400-500 kg propellant vs chemical, but takes 6-9 months to reach GEO from GTO. Examples: PPS-1350 (Snecma, Sentinel-5P), SPT-100 (Russian, Globalstar), BHT-600 (Busek, LunaH-Map), Hall thrusters on Starlink V2 Mini (SpaceX custom design)."},

    {"id": "propulsion-ion-001", "domain": "propulsion",
     "title": "Ion Propulsion Systems",
     "source": "Rakel, Ion Propulsion; NASA Dawn/Hayabusa documentation",
     "text": "Gridded ion thrusters accelerate ions using electrostatic grids. Higher Isp than Hall thrusters (3,000-10,000 s) but lower thrust density. NSTAR (NASA Solar Technology Application Readiness): flew on Deep Space 1 and Dawn. Isp: 3,100 s at 2.3 kW; thrust: 92 mN. NEXT (NASA Evolutionary Xenon Thruster): Isp 4,190 s, 236 mN, 6.9 kW. Flew on Lucy mission (2021). Japan IEPC (Hayabusa 1/2): μ10 ion engines, microwave ionization, flew to asteroid Itokawa and Ryugu, returned samples. Hayabusa2 thrust: 8 mN per thruster, 4 engines nominal. ESA Artemis satellite: used ion propulsion (RITA-10) to rescue failed GTO insertion, successfully reached GEO using only electric propulsion over 18 months. Mission design implication: long burn times require careful trajectory optimization for time-constrained missions."},

    {"id": "propulsion-solid-001", "domain": "propulsion",
     "title": "Solid Rocket Motor Design and Performance",
     "source": "Sutton, Rocket Propulsion Elements; NASA SRB documentation",
     "text": "Solid rocket motors burn a solid propellant grain of fuel and oxidizer cast together. Ammonium Perchlorate Composite Propellant (APCP): ammonium perchlorate (AP, oxidizer) 65-70%, aluminum powder (fuel) 16-20%, HTPB binder 12-15%, additives. Performance: Isp 260-295 s, thrust density 1-5 MN/m². Grain geometry determines thrust curve: cylindrical bore = constant thrust; star pattern = neutral (progressive/regressive tunable); finocyl = complex shaped. Space Shuttle SRBs: 11.6 MN each, largest solid motors ever flown. Castor 120 (Orbital ATK): 1.7 MN, used on Pegasus XL, Taurus. Solid advantages: simplicity, storability, high T/W, no turbopumps. Disadvantages: cannot throttle (once ignited, burns to completion), high chamber pressure requires heavy casing, toxic exhaust (HCl), burn-time limited by case integrity."},

    {"id": "propulsion-cryo-storage-001", "domain": "propulsion",
     "title": "Cryogenic Propellant Storage",
     "source": "NASA Technical Reports; Sutton",
     "text": "Cryogenic propellants (LH2 at -253°C, LOX at -183°C, LCH4 at -162°C) require specialized storage. Insulation: vacuum-jacketed tanks with multilayer insulation (MLI, alternating aluminized mylar and dacron). Boil-off rate: LH2 tanks without active cooling lose 1-3% per day. For long-duration missions (>6 months), active cryo-coolers required (Stirling, pulse tube). Zero-boil-off (ZBO) technology: NASA ISP for lunar/Mars propellant depots. Propellant management: microgravity environment prevents settling by gravity — surface tension devices (screen, vanes) or settle burns used. Liquid stratification: temperature gradients in large tanks; mixing prevents hot spot boil-off. Deep space storage: deep cryo at <20 K for ZBO LH2. Operational considerations: ground time on pad adds boil-off — SpaceX Falcon 9 loads LOX just before launch (densified LOX at -206°C increases density 6%, improving performance)."},

    {"id": "propulsion-green-001", "domain": "propulsion",
     "title": "Green Propellant Alternatives",
     "source": "PRISMA mission; Aerojet Rocketdyne AF-M315E documentation; ESA",
     "text": "Traditional storable propellants (hydrazine, UDMH, MMH) are highly toxic and carcinogenic, requiring expensive handling. Green propellant alternatives: AF-M315E (ASCENT, Aerojet): hydroxylammonium nitrate-based ionic liquid. Isp 250 s (25% better than hydrazine), higher density, lower vapor pressure, safer handling. Flew on NASA GPIM (Green Propellant Infusion Mission) 2019. LMP-103S (HPGP, Bradford ECAPS): ammonium dinitramide (ADN)-based. Isp 252 s. Flew on SkySat-1 and PRISMA (Sweden). Electric propulsion in LEO constellations: reduces toxic propellant mass on orbit, reducing debris risk from residual propellant in decommissioned satellites. H2O2 (hydrogen peroxide): high-concentration (98%) HTP used as monoprop (Isp ~165 s) or in bi-prop with kerosene. Rocket Lab Rutherford uses electric pump-fed LOX/RP-1, essentially green but still RP-1."},

    {"id": "propulsion-upper-stage-001", "domain": "propulsion",
     "title": "Upper Stage Engine Technology",
     "source": "ULA Centaur documentation; ESA HM-7B; SpaceX documentation",
     "text": "Upper stage engines operate in vacuum with large nozzle expansion ratios. Key upper stages: Centaur (ULA): RL-10 engine (Aerojet), LH2/LOX, Isp 450.5 s, 99.1 kN thrust. Highest performing American upper stage. Used on Atlas V and Vulcan. Restartable: up to 15 restarts. RL-10C-3 for Vulcan: 109.9 kN, 465.5 s Isp. Falcon 9 upper stage: single Merlin Vacuum, 934 kN, 348 s Isp. Single restart (coast phase capability for multiple payload delivery). Ariane 6 Vinci engine (upper stage): 180 s burn, multiple restarts, LH2/LOX, 457 s Isp. New Glenn upper stage: BE-3U (Blue Origin), LH2/LOX, 710 kN, 470 s Isp. Critical for direct injection missions: upper stage performs circularization and orbit raising, determining final orbit accuracy."},

    {"id": "propulsion-nozzle-001", "domain": "propulsion",
     "title": "Rocket Nozzle Design",
     "source": "Sutton, Rocket Propulsion Elements; AIAA propulsion texts",
     "text": "Rocket nozzles convert combustion gas thermal energy to kinetic energy. De Laval nozzle: converging-diverging shape. Throat: minimum area, sonic velocity (Mach 1). Expansion ratio ε = Ae/At. Optimal expansion: exit pressure = ambient pressure for maximum efficiency. At sea level: optimal ε ~15-20. In vacuum: larger ε preferred (up to 100 for upper stages). Nozzle exit velocity v_e = sqrt(2γ/(γ-1) × R×T_c/M × (1 - (pe/pc)^((γ-1)/γ))). Isp = v_e/g0 + (pe-pa)×Ae/(ṁ×g0). Materials: nickel superalloys (Inconel), refractory metals (tungsten), carbon-carbon composites, ablative materials (charring). Cooling: regenerative (fuel or oxidizer flows through jacket, common for LH2), film cooling, radiation cooling (for small thrusters). Bell nozzle: contoured for uniform exit flow. Extendable nozzles: deployed in vacuum for improved performance (Ariane upper stage)."},

    {"id": "propulsion-combustion-001", "domain": "propulsion",
     "title": "Rocket Combustion Instability",
     "source": "Sutton; Rocket Combustion Chamber Design texts; Saturn F-1 history",
     "text": "Combustion instability is a primary design challenge in high-thrust engines. Types: (1) Low-frequency (chug, 10-400 Hz): driven by propellant feed system oscillations. Solved by orifice sizing, accumulator/Helmholtz resonators. (2) Medium-frequency (buzz, 400-1000 Hz): droplet vaporization rate oscillations. (3) High-frequency (screech, 1000+ Hz): acoustic modes in combustion chamber. Most destructive — heat transfer increases catastrophically. Saturn F-1 engine (Apollo): extensive combustion instability testing required, eventually solved by baffled injector plate dividing chamber into compartments. Modern mitigation: acoustic resonator cavities (Helmholtz resonators), injector orifice pattern optimization (unlike-doublet vs. like-doublet), chamber geometry. SpaceX testing philosophy: test-to-failure many engines to understand margins. Raptor development required extensive injector redesign to achieve stability at 300 bar."},

    {"id": "propulsion-restart-001", "domain": "propulsion",
     "title": "Engine Restart and Coast Phase Operations",
     "source": "ULA Centaur operations; SpaceX Falcon documentation",
     "text": "Multiple engine restarts are required for complex missions (direct GTO injection, multiple payload deployment, de-orbit). Technical challenges: (1) Cryogenic propellant settling: in zero-g, liquid moves unpredictably. Settle burn (small thrust) or surface tension devices required before restart. (2) Ignition reliability: spark igniters, hypergolic slug ignition, or torch igniters used. Failure modes: igniters, propellant conditioning, start transient. (3) Thermal management: engine cools during coast; requires pre-conditioning (circulation or conditioning burns). (4) Propellant mass management: accurate tracking of consumed propellant for guidance. FMEA for restart: each restart is a critical event; RL-10 qualifies for up to 15 restarts. Falcon 9 upper stage: single restart for standard missions (LEO parking orbit + circularization or GTO insertion). SpaceX extended coast missions (direct GEO, interplanetary): use propellant settling, 6-hour coast demonstrated."},

    {"id": "propulsion-electric-sat-001", "domain": "propulsion",
     "title": "Satellite Electric Propulsion Architecture",
     "source": "Boeing 702SP documentation; ESA Alphabus; SpaceX Starlink",
     "text": "All-electric GEO satellites use only electric propulsion for all maneuvers including orbit raising. Boeing 702SP: 2 xenon ion thrusters (XIPS-25), each 165 mN, 3,500 s Isp. 4 thrusters total (2 operating, 2 redundant). ABS-3A and Eutelsat 115 West B: first all-electric GEO spacecraft (2015). Orbit raising from GTO to GEO: 200-300 days (vs 2 weeks with chemical apogee motor). Mass savings: 400-500 kg propellant (vs bipropellant GEO insertion). Station-keeping: Hall thruster 50 mN for N-S and E-W. Starlink V2: Hall thrusters, krypton propellant (cheaper than xenon, slightly lower Isp). OneWeb: plasma thrusters from Safran (SPT-50M). Benefits of electric propulsion in constellations: lower unit mass per satellite, lower launch cost (more satellites per launch), lower collision risk from residual propellant in decommissioned satellites."},

    # ─── COMMUNICATIONS (25 chunks) ──────────────────────────────────────────

    {"id": "comms-link-budget-001", "domain": "communications",
     "title": "RF Link Budget Fundamentals",
     "source": "Haykin, Communication Systems; Larson & Wertz SMAD",
     "text": "A link budget accounts for all gains and losses in a communications path. Received power: Pr = Pt + Gt - Lfs - La + Gr where all in dB. Pt = transmit power (dBW), Gt = transmit antenna gain (dBi), Lfs = free-space path loss = 20×log10(4πR/λ) dB, La = atmospheric/rain attenuation (dB), Gr = receive antenna gain (dBi). Link margin = Pr - (minimum Pr for acceptable BER). Example: LEO satellite at 550 km, 20 W transmitter (13 dBW), 6 dBi antenna, 28 GHz (λ=10.7 mm): Lfs = 20×log10(4π×550,000/0.0107) = 176 dB. With 40 dBi ground antenna: Pr = 13+6-176+40 = -117 dBW. Noise power N = kTB = -228.6+20log10(T)+10log10(B). Required Eb/N0 for QPSK BER 10^-6: ~10.5 dB."},

    {"id": "comms-frequency-bands-001", "domain": "communications",
     "title": "Satellite Communication Frequency Bands",
     "source": "ITU Radio Regulations; CCSDS; Larson & Wertz SMAD",
     "text": "Frequency bands for satellite communications: VHF (30-300 MHz): TT&C for LEO smallsats, low data rate, minimal rain attenuation. UHF (300 MHz-1 GHz): military (SATCOM UHF), mobile satellite services. L-band (1-2 GHz): GPS/GNSS (1.176-1.575 GHz), Iridium (1616-1626 MHz), Inmarsat voice. S-band (2-4 GHz): ISS TT&C, NASA Near Space Network, weather satellites. X-band (8-12 GHz): military (MILSATCOM, WGS), SAR (Sentinel-1: 9.65 GHz), some commercial. Ku-band (12-18 GHz): direct broadcast TV (12-12.75 GHz), VSATs, Starlink user links (10.7-12.7 GHz). Ka-band (26.5-40 GHz): high-throughput satellite (HTS), Starlink gateway (26-40 GHz), ViaSat. Rain attenuation: 0.01% of time, 28 GHz: 20 dB for tropical; Ku-band: 5-10 dB. Regulatory: ITU RR coordinates global spectrum. Filing priority by date; coordination required with neighboring satellites."},

    {"id": "comms-fso-001", "domain": "communications",
     "title": "Free-Space Optical Communications",
     "source": "NASA LLCD; LCRD documentation; Hemmati, Deep Space Optical Communications",
     "text": "Free-space optical (FSO) laser communications offer 10-1000× higher data rates than RF for equivalent mass/power. No spectrum licensing required. Key parameters: wavelength 1550 nm (telecom C-band) or 1064 nm; beam divergence ~10 μrad (vs RF 1-10°); pointing, acquisition, and tracking (PAT) critical to ±1 μrad accuracy. LLCD (Lunar Laser Communication Demonstration, 2013): 622 Mbps downlink from lunar orbit — 6× faster than RF on same-size aperture. LCRD (Laser Communications Relay Demonstration, 2021): GEO relay, 1.2 Gbps. LCOTS (Laser Communication Optical Terminal for Space): planned for ISS. SpaceX Starlink inter-satellite links (ISL): laser links between satellites, enabling low-latency global routing (Starlink already operating laser ISLs in Gen 1 satellites over polar regions). Challenges: atmospheric absorption (clouds), pointing precision, background light rejection."},

    {"id": "comms-modulation-001", "domain": "communications",
     "title": "Modulation and Coding for Satellite Links",
     "source": "CCSDS 131.0-B-3; Proakis, Digital Communications",
     "text": "Modulation schemes for satellite links trade spectral efficiency vs. power efficiency. BPSK (Binary PSK): 1 bit/symbol, Eb/N0 = 9.6 dB for BER 10^-6, most power efficient. QPSK (Quadrature PSK): 2 bits/symbol, Eb/N0 = 9.6 dB — same as BPSK but double spectral efficiency. 8PSK: 3 bits/symbol, Eb/N0 = 14 dB. 16APSK: 4 bits/symbol, used in DVB-S2 for HTS. 64APSK: 6 bits/symbol, latest DVB-S2X standard. Channel coding (error correction): Reed-Solomon (legacy), Turbo codes (CCSDS 231.0-B-4), LDPC (Low-Density Parity Check, DVB-S2, CCSDS 131.0-B-3) — near Shannon limit. Coding gain: LDPC with code rate 1/2 provides ~7 dB coding gain at BER 10^-6. Adaptive Coding and Modulation (ACM): DVB-S2 feature, adjusts modulation/coding rate with link conditions, maximizing throughput in clear sky while maintaining link in rain."},

    {"id": "comms-delay-001", "domain": "communications",
     "title": "Latency in Satellite Communications",
     "source": "ITU-T G.114; ITU-R S.1709; SpaceX Starlink technical documentation",
     "text": "One-way propagation delay = distance/c. GEO (35,786 km): one-way ~119 ms, round-trip ~238 ms. This delay makes GEO unsuitable for real-time applications (gaming, video calls): ITU recommends <150 ms one-way for voice quality. LEO (550 km): one-way ~1.8 ms. Starlink: typical round-trip latency 20-60 ms (including processing, routing, ground segment). MEO (20,200 km GPS altitude): ~67 ms one-way. Doppler effect: LEO satellite at 7.6 km/s produces frequency shift: Δf/f = v/c × cos(θ). At 550 km pass directly overhead: ±6 kHz at 1 GHz (L-band). Satellite internet latency comparison: GEO HTS (ViaSat-3, HughesNet): 600-800 ms; OneWeb LEO: 60-100 ms; Starlink: 20-60 ms; fiber: 1-10 ms. Key applications affected by GEO latency: TCP/IP throughput (RTT affects congestion window), VoIP quality, gaming, financial trading."},

    {"id": "comms-doppler-001", "domain": "communications",
     "title": "Doppler Compensation in LEO Satellite Links",
     "source": "CCSDS; ITU; operational documentation",
     "text": "LEO satellites at 7.5 km/s orbital velocity produce significant Doppler shift on radio signals. Maximum Doppler rate: v×cos(0°)/λ = 7,500/λ Hz at closest approach for overhead pass. At 437 MHz (UHF): ±10.8 kHz peak. At 2.4 GHz (S-band): ±60 kHz. At 10 GHz (X-band): ±250 kHz. Rate of change: maximum dopplerrate near elevation 0° horizon crossing. Compensation: ground-station receiver applies Doppler prediction from TLE; correction applied to local oscillator. Residual Doppler error after prediction: <100 Hz for well-tracked satellites. Satellite side: frequency-invariant modulation (BPSK, OQPSK) or pre-distorted transmit frequency based on predicted ground station location. Spread spectrum (direct sequence spread spectrum, DSSS): large bandwidth (10-50 MHz) tolerates Doppler without explicit correction. GPS signal uses DSSS for this reason. FHSS (frequency hopping): avoids by rapid frequency changes."},

    {"id": "comms-antenna-001", "domain": "communications",
     "title": "Satellite Antenna Types and Gain",
     "source": "Balanis, Antenna Theory; Larson & Wertz SMAD",
     "text": "Antenna gain G = η × (4π/λ²) × A for aperture area A and efficiency η. Types: Omni/whip (0 dBi): omnidirectional, for TT&C during tumble/anomaly. Patch (5-7 dBi): small, low profile, used for GPS, smallsat UHF. Helix (12-15 dBi): circularly polarized, used for LEO ground stations. Yagi (10-20 dBi): directional, amateur radio LEO. Parabolic dish (30-60 dBi): used for GEO, deep space. Phased array (electronically steerable): modern HTS terminals (Starlink user terminal), aircraft/maritime terminals. Phased array allows instantaneous beam steering without mechanical movement, critical for LEO tracking. Phased array aperture ~30 cm, gain ~33 dBi for Starlink Gen 2 terminal. Active electronically scanned array (AESA): each element has T/R module with individual amplitude/phase control. Massive MIMO: satellite uses hundreds of antenna elements for spatial multiplexing and multi-beam formation."},

    {"id": "comms-hts-001", "domain": "communications",
     "title": "High-Throughput Satellite Architecture",
     "source": "ViaSat; Hughes; Intelsat; Eutelsat documentation",
     "text": "High-Throughput Satellites (HTS) use frequency reuse across multiple spot beams to achieve 10-100× more capacity than wide-beam satellites. Architecture: dozens to hundreds of narrow spot beams (0.5-2° beamwidth) each reusing the same frequency band. Each beam covers ~200-500 km footprint. Ka-band preferred for high bandwidth. Gateways: multiple large ground stations interconnect satellite spot beams to internet backbone. Capacity per satellite: ViaSat-3 (2023): >1 Tbps (entire North America). EchoStar 105/SES-11: 150 Gbps. Technology enablers: digital beamforming (DBF), onboard processing (regenerative payload), frequency reuse factor 3-4. User terminal: 60-90 cm dish for GEO HTS. Starlink comparison: 1,000+ satellite LEO network vs single GEO satellite — different architecture, both achieving Tbps aggregate capacity. HTS economics: cost per Mbps dropped 90% 2010-2020 due to HTS, enabling broadband over satellite at competitive prices."},

    {"id": "comms-crosslinks-001", "domain": "communications",
     "title": "Inter-Satellite Links",
     "source": "Iridium NEXT; Starlink; Teledesic documentation",
     "text": "Inter-satellite links (ISL) or crosslinks allow satellites to communicate directly without going through a ground station. Iridium NEXT: Ka-band ISLs (23.18-23.38 GHz), 4 crosslinks per satellite (2 in-plane, 2 cross-plane), 10 Mbps. Enable global coverage with minimal ground infrastructure. Starlink (Gen 1): laser ISLs added on later batches, ~100 Gbps per link, enabling pole-to-pole routing. Advantage: message routed in space at c vs ground fiber (light travels 47% faster in vacuum than glass), enabling lower latency transatlantic/transpacific routes. SpaceX Wall Street trading advantage: claimed <1 ms advantage on London-New York route. Teledesic (proposed 1990s, cancelled): planned 840 satellite mesh with Ka-band ISLs — too expensive then; LEO ISL technology now mature. O3b mPOWER: MEO HTS system with dual-frequency ISLs. Technical challenge: beam pointing as satellite orbits require rapid angular rate changes across ISL."},

    {"id": "comms-satcom-protocols-001", "domain": "communications",
     "title": "Satellite Communication Protocols and Standards",
     "source": "DVB-S2/S2X standard; CCSDS; ETSI",
     "text": "DVB-S2 (Digital Video Broadcasting-Satellite Second Generation): dominant standard for satellite broadband. Features: LDPC+BCH coding, ACM (adaptive coding/modulation), 32 modulation/coding combinations, spectral efficiency 0.49-3.70 bits/s/Hz. Used by HTS, VSAT, direct-to-home (DTH). DVB-S2X: extension with finer modulation granularity, higher order modulation (64APSK, 128APSK), improved spectral efficiency. DVB-RCS2 (Return Channel via Satellite): standard for MF-TDMA uplink. CCSDS Proximity-1 (211.0-B-5): short-range inter-spacecraft links. CCSDS TM Space Data Link Protocol (131.0-B-3): standard telemetry downlink. CCSDS TC Space Data Link Protocol (232.0-B-4): telecommand uplink. LoRa (Long Range): unlicensed IoT protocol, used in LPWAN smallsats (Lacuna Space, Sateliot) for IoT connectivity. Satellite IP standards: IPoS (IP over Satellite), TS-125 (ETSI standard). PEP (Performance Enhancing Proxy): TCP splitting at ground station to compensate for satellite latency."},

    {"id": "comms-ground-station-networks-001", "domain": "communications",
     "title": "Commercial Ground Station Networks",
     "source": "AWS Ground Station; Azure Orbital; KSAT; SSC documentation",
     "text": "Commercial ground station networks provide satellite operators API-based access to global antenna infrastructure. AWS Ground Station: globally distributed antennas (11 sites), 10+ partner sites via Virtual Private Ground Station. Integrates with AWS cloud for direct downlink-to-compute workflow. Pricing: per minute of contact time. Azure Orbital: Microsoft equivalent, integrates with Azure. Supported satellites: Aqua, Terra, GOES, Landsat, custom. KSAT (Kongsberg Satellite Services): world's largest commercial ground network. 27 antenna sites. Specializes in polar LEO coverage (Svalbard). 65,000 passes per year. SSC (Swedish Space Corporation): polar-focused, 15 sites. Scientific and commercial missions. iGS (Integrated Ground Segment): antenna-as-a-service model with standardized interfaces. Value proposition: eliminate capital cost of own ground network (typically $5-20M per site), elastic capacity, global coverage. Telemetry/command latency: ground station 'windows' must align with satellite passes — commercial networks increase window frequency."},

    # ─── EARTH OBSERVATION (25 chunks) ───────────────────────────────────────

    {"id": "eo-resolution-001", "domain": "earth_observation",
     "title": "Spatial Resolution in Earth Observation",
     "source": "SMAD; Lillesand & Kiefer, Remote Sensing; Sentinel-2 documentation",
     "text": "Spatial resolution defines the minimum ground feature size detectable. Ground Sample Distance (GSD): pixel size on ground, related to detector pixel size, focal length, altitude. WorldView-3 (DigitalGlobe/Maxar): 0.31 m panchromatic at 617 km — highest commercial resolution. Planet SkySat: 0.5 m. SPOT-7: 1.5 m. Sentinel-2: 10 m (VIS/NIR), 20 m (SWIR), 60 m (atmospheric bands). Landsat 8/9: 30 m (OLI). MODIS: 250 m-1 km. Resolution vs applications: <0.5 m: military intelligence, change detection; 1-5 m: urban mapping, vessel detection; 10-30 m: agricultural monitoring, land cover; 100-500 m: weather, large-scale forestry; >1 km: global climate, ocean color. Nyquist sampling: GSD should be ≤ 0.5 × target resolution for reliable detection. MTF (modulation transfer function): system-level resolution metric accounting for diffraction, optical aberrations, detector, platform jitter."},

    {"id": "eo-spectral-001", "domain": "earth_observation",
     "title": "Spectral Bands and Remote Sensing Applications",
     "source": "NASA EO-1 Hyperion; Sentinel-2 documentation; Landsat documentation",
     "text": "Spectral bands in Earth observation satellites: Blue (450-520 nm): water penetration, coastal mapping, aerosol. Green (520-600 nm): vegetation chlorophyll reflectance peak, sediment. Red (630-690 nm): vegetation absorption (chlorophyll). Red Edge (705-745 nm): sensitive to vegetation stress — unique to Sentinel-2. NIR (850-900 nm): vegetation reflectance high, water absorption. SWIR 1 (1550-1750 nm): moisture content, mineral discrimination. SWIR 2 (2080-2350 nm): mineral mapping, geology. Thermal IR (10,300-11,300 nm): land surface temperature, fire detection. Derived indices: NDVI = (NIR-Red)/(NIR+Red): vegetation density; NDWI = (Green-NIR)/(Green+NIR): water bodies; NDSI = (Green-SWIR)/(Green+SWIR): snow cover. Hyperspectral: hundreds of narrow bands (e.g., Hyperion: 220 bands at 10 nm width). Applications: mineral identification, precision agriculture, urban heat islands."},

    {"id": "eo-sar-001", "domain": "earth_observation",
     "title": "Synthetic Aperture Radar Fundamentals",
     "source": "Ulaby, SAR Marine User's Manual; Sentinel-1 documentation",
     "text": "SAR uses radar pulses and platform motion to synthesize a large aperture, achieving high resolution regardless of illumination or cloud cover. Wavelengths: C-band (5.4 GHz/5.6 cm): Sentinel-1, RADARSAT-2; L-band (1.2 GHz/23 cm): ALOS-2, NISAR; X-band (9.6 GHz/3.1 cm): TerraSAR-X, CSK, COSMO-SkyMed. Resolution: along-track (azimuth) resolution ≈ antenna_length/2 (synthesized aperture). Range resolution = c/(2B) where B = pulse bandwidth. TerraSAR-X: 0.25 m spotlight mode resolution. SAR polarizations: HH, VV, HV, VH; quad-pol for maximum information. Applications: maritime (vessel detection regardless of weather), deforestation monitoring, earthquake damage mapping (coherence change detection), ice sheet velocity, subsidence (InSAR). InSAR (Interferometric SAR): phase difference between two SAR images reveals surface deformation to mm precision. Used for volcanic inflation, groundwater extraction subsidence monitoring."},

    {"id": "eo-sentinel-001", "domain": "earth_observation",
     "title": "ESA Copernicus Sentinel Constellation",
     "source": "ESA Copernicus documentation; Sentinel mission documentation",
     "text": "ESA Copernicus program Sentinel constellation provides free global Earth observation data: Sentinel-1 (A/B, now C/D): C-band SAR, 6-day repeat (A+B), swath 250 km in IW mode at 10 m resolution. Primary applications: land/sea monitoring. Sentinel-1B failed 2022 (single satellite operations until 1C/D). Sentinel-2 (A/B): multispectral optical, 13 bands (10/20/60 m), 290 km swath, 5-day repeat (A+B). Global land monitoring, agriculture, coastal. Sentinel-3 (A/B): ocean and land, OLCI (300 m ocean color, 21 bands), SLSTR (sea surface temperature), SRAL (radar altimeter). Sentinel-5P: atmospheric composition, TROPOMI instrument, daily global mapping, 3.5×5.5 km resolution. Methane, NO2, O3, SO2, CO. Sentinel-6 (Michael Freilich): ocean altimetry, continuing Jason-2/3 legacy, 10-day repeat. Open data policy: all Sentinel data free, fostering commercial value-added industry. Copernicus Data Space Ecosystem: cloud platform for analysis."},

    {"id": "eo-change-detection-001", "domain": "earth_observation",
     "title": "Change Detection and Time Series Analysis",
     "source": "Remote sensing literature; Planet Labs; ESA CCI",
     "text": "Change detection identifies differences in Earth surface between image acquisitions. Methods: image differencing (NIR2 - NIR1), band rationing, NDVI differencing, principal component analysis (PCA), change vector analysis. Time series: Planet constellation (200+ satellites) provides daily global coverage, enabling sub-weekly change detection. Applications: deforestation (Global Forest Watch uses Landsat/Sentinel-2, detects loss >0.09 ha), crop monitoring (EU CAP compliance, crop type mapping), oil spill detection (SAR), surface water (JRC Global Surface Water Landsat archive, 1984-present). Machine learning for change detection: convolutional neural networks (CNNs) trained on labeled change examples outperform traditional thresholds. Sentinel hub EO Browser: web platform for accessing and comparing multi-temporal Sentinel data. Commercial analytics: Planet, Maxar, BlackSky, provide change analytics APIs for urban monitoring, infrastructure, agriculture."},

    {"id": "eo-ocean-color-001", "domain": "earth_observation",
     "title": "Ocean Color Remote Sensing",
     "source": "IOCCG; NASA MODIS Ocean Color documentation; Sentinel-3 OLCI",
     "text": "Ocean color satellites measure the spectral reflectance of the ocean surface to infer water quality and biology. Chlorophyll-a concentration indicates phytoplankton biomass (primary production). Sensors: MODIS on Terra/Aqua (250 m-1 km, daily global), SeaWiFS (historical), Sentinel-3 OLCI (300 m, 21 bands), PACE (2024, 5 nm spectral resolution 340-890 nm). Algorithm: OC3M algorithm: Chl-a = 10^(a0 + a1×R + a2×R² + ...) where R = log10(Rrs(490)/Rrs(555)). Applications: fisheries management (fish follow chlorophyll fronts), harmful algal bloom detection (HAB), carbon cycle monitoring, water quality. CDOM (colored dissolved organic matter): affects ocean color in coastal waters. Atmospheric correction: major challenge — only ~10% of top-of-atmosphere signal is from ocean; 90% is atmospheric. BRDF correction, aerosol models critical. Open data: NASA OceanColor web portal provides MODIS, SeaWiFS, PACE data."},

    {"id": "eo-tasking-001", "domain": "earth_observation",
     "title": "Satellite Tasking and Collection Planning",
     "source": "Planet Labs; Maxar; SPOT documentation",
     "text": "Tasking systems schedule Earth observation satellite collections. Competing objectives: maximize revenue (priority customers), maximize coverage (blanket mode), avoid conflicts (solar angle, cloud cover, off-nadir limits). Collection modes: strip (along-track swath, continuous), area (multiple strips), point target (maximum integration time at specific location), stereo (two angles for 3D reconstruction). Off-nadir pointing: typical limit 30-45° from nadir. At 45° off-nadir from 500 km: ground sample footprint elongated, GSD degraded by 1/cos(45°) ≈ 1.4×. Access window: time window when satellite can view target above minimum elevation. Access frequency depends on: orbit ground track repeat period, latitude (polar satellites revisit poles more frequently), number of satellites. Planet Dove: every satellite passes over every point on Earth daily (combined 200+ satellite fleet). Commercial tasking APIs: Planet Tasking API, Maxar TaskerAPI — orders collection within days. Emergency response: push-tasking protocol for disaster response within hours."},

    {"id": "eo-lidar-001", "domain": "earth_observation",
     "title": "LiDAR and Altimetry from Space",
     "source": "ICESat-2 documentation; GEDI documentation; CALIPSO",
     "text": "Space-based LiDAR uses laser pulses timed to measure range to surface. ICESat-2 (2018): ATLAS instrument, 532 nm green laser, 10 kHz pulse rate, measures ice sheet elevation to 1 cm precision. Three pairs of beams, 91-day repeat orbit. Applications: ice sheet mass balance (Greenland losing 280 Gt/year ice confirmed by ICESat-2), sea ice thickness, vegetation canopy height. GEDI (Global Ecosystem Dynamics Investigation, 2019, ISS): 1064 nm, full-waveform LiDAR, 25 m footprint, measures forest canopy height and structure globally. 10 billion measurements. CALIPSO (2006): aerosol and cloud LiDAR. 532/1064 nm backscatter. Vertical profiles of aerosols, clouds, polar stratospheric clouds. MOLA (Mars Orbiter Laser Altimeter): mapped Mars topography to ~1 m vertical resolution. Photon-counting LiDAR (ICESat-2 ATLAS): single photon sensitivity, allows global coverage from LEO with limited laser power."},

    # ─── COMMERCIAL SPACE (20 chunks) ────────────────────────────────────────

    {"id": "commercial-newspace-001", "domain": "commercial_space",
     "title": "New Space Business Model Evolution",
     "source": "Space Foundation; Bryce Space; CB Insights",
     "text": "New Space represents a fundamentally different approach to space business: commercial-first, venture-funded, iterative development. Old Space characteristics: government prime contractor, cost-plus contracts, 10-15 year development cycles, heritage components, MIL-SPEC requirements, conservative testing. New Space characteristics: commercial off-the-shelf (COTS), fixed-price contracts, 1-3 year development, agile software development, hardware-in-the-loop simulation, test-to-failure philosophy. Key enablers: miniaturization (smartphones with GPS, IMU, MEMS), launch cost reduction (Falcon 9 reuse), cloud computing (on-demand ground infrastructure), additive manufacturing (complex metal parts), commercial components (GPU processors radiation-tolerant via software). Venture investment in space: $10.3B in 2021 (record). Key investors: Andreessen Horowitz, Founders Fund, Bessemer, SoftBank, Google. Investment categories: launch (35%), satellites (40%), downstream (25%)."},

    {"id": "commercial-rideshare-001", "domain": "commercial_space",
     "title": "Rideshare Launch Market",
     "source": "Spaceflight Inc.; Exolaunch; SpaceX Transporter documentation",
     "text": "Rideshare launches carry multiple payloads on a single rocket, dramatically reducing cost for smallsats. SpaceX Transporter series: dedicated Falcon 9 SSO rideshare, $5,500/kg to 500 km SSO. Transporter-1 (Jan 2021): 143 spacecraft record, Transporter-9 (2023): 90 spacecraft. Exolaunch: integration and deployment services. Satellite deployers: 6U/12U/16U ISIPOD, 6U Exopod, custom. D-Orbit ION carrier: orbital transfer vehicle deployed by Transporter, then re-delivers customer satellites to precise orbits. Spaceflight Inc.: aggregates payloads, books rideshare. ESPA (EELV Secondary Payload Adapter): ring adapter for secondary payloads on US government launches. NASA CubeSat Launch Initiative (CSLI): free launches for educational CubeSats. Vega-C (ESA): SSMS (Small Spacecraft Mission Service) adapter. PSLV (ISRO): multiple smallsat launch history (PSLV-C37: 104 satellites record 2017). Rideshare limitations: fixed orbit (usually SSO), limited post-deployment maneuverability."},

    {"id": "commercial-data-economy-001", "domain": "commercial_space",
     "title": "Space Data Economy and Analytics",
     "source": "EO market analysis; Planet; Spire; DigitalGlobe",
     "text": "The space data economy transforms raw satellite data into intelligence products. Revenue model evolution: imagery → analytics → APIs → insights. Planet Labs business model: daily global imagery subscription ($2-20M/year for government agencies, analytics APIs for commercial). Products: Basemaps (quarterly global mosaic), Scene (individual captures), Monitoring (change detection). Spire Global: maritime (AIS vessel tracking), aviation (ADS-B aircraft tracking), weather (GNSS radio occultation). Revenue from data licensing, APIs, and analytics. Market segments: agriculture (yield forecasting, crop monitoring), insurance (natural disaster assessment), financial (commodity price prediction from crop monitoring), security/defence (change detection, vessel tracking). ESA Earth observation market: €2.5B annual revenue in Europe (2020). GMES/Copernicus value: €131B economic return on €1.4B investment (ESA estimate). Downstream applications: machine learning on satellite imagery, computer vision for automated feature extraction."},

    {"id": "commercial-spac-001", "domain": "commercial_space",
     "title": "SPAC Transactions in Space Industry",
     "source": "SEC filings; SpaceNews; CB Insights",
     "text": "Special Purpose Acquisition Companies (SPACs) became popular for space startups 2020-2022. SPAC structure: shell company raises IPO capital, then acquires target company. Advantage for space: enables public market access without traditional IPO timeline; provides funding certainty during development; enables deal at valuation based on forward projections. Notable space SPACs: AST SpaceMobile (ASTS, 2021, $462M), Spire Global (SPIR, 2021, $216M), BlackSky Technology (BKSY, 2021, $316M), RocketLab (RKLB, 2021, $777M), Satellogic (SATL, 2022, $270M), Virgin Orbit (VORB, 2021, $483M — bankrupt 2023). SPAC performance: space SPACs significantly underperformed post-merger (industry average -70% by 2022 from peak). Causes: over-optimistic revenue projections, development delays, launch delays, market saturation. Lesson: space timelines and capital requirements routinely exceed projections. Traditional IPO alternatives remain (Planet Labs IPO 2021 via direct listing)."},

    {"id": "commercial-sso-market-001", "domain": "commercial_space",
     "title": "Commercial SSA Market Emergence",
     "source": "LeoLabs; ExoAnalytic; SpaceNav; Slingshot Aerospace documentation",
     "text": "Commercial SSA providers emerged to supplement US government Space-Track.org data with higher accuracy, more objects, and commercial service. LeoLabs: phased array radar network (7 sites: New Zealand, Costa Rica, Texas, Alaska, others). Tracks LEO objects to 2 cm size. Commercial API: conjunction screening, pass predictions, precision orbit data. 14,000+ objects tracked. ExoAnalytic Solutions: 300+ optical telescopes globally for GEO and MEO. Real-time GEO catalog (CSpOC supplement). SpaceNav (now part of Aalyria): SSA data fusion. Slingshot Aerospace: data fusion, AI-based conjunction screening. Hawkeye360: cluster satellites for RF signal detection and geolocation. DLR German Space Operations Center: European SSA. EU SST (Space Surveillance and Tracking): network of European sensors. Value proposition over Space-Track: commercial SLAs, precision data, more objects tracked, analytics integrated, API access. Pricing: $50K-$1M/year depending on service level."},

    {"id": "commercial-insurance-001", "domain": "commercial_space",
     "title": "Space Insurance Market",
     "source": "Lloyd's of London; Marsh; Munich Re space insurance data",
     "text": "Space insurance covers launch risk, in-orbit anomalies, and third-party liability. Market size: $600-900M annual premium globally. Launch insurance: covers total loss from launch failure. Premium: 5-10% of satellite value (higher for new vehicles). GEO satellite value: $200-400M → premium $10-40M/launch. In-orbit insurance: covers partial/total loss from on-orbit failure. Premium: 0.5-1.5% per year. Typical GEO satellite insured for $150-200M. Third-party liability: required by most national regulations. Covers damage to ground/aircraft/other satellites. US government unlimited liability for US launches — private operators indemnified up to $1.5B per launch. Lloyd's of London: largest space insurance market. Munich Re, Swiss Re: reinsurance. Actuarial data: ~5% of satellites experience total loss or partial loss requiring insurance claim annually. Emerging challenges: constellation insurance (thousands of satellites, correlated failure modes), mega-constellation collision risk, cybersecurity. SpaceX: reportedly self-insures Starlink constellation."},

    {"id": "commercial-launch-pricing-001", "domain": "commercial_space",
     "title": "Launch Vehicle Pricing and Cost Evolution",
     "source": "FAA AST Annual Compendium; public price lists; Bryce Space",
     "text": "Launch cost evolution driven by SpaceX reusability and commercial competition: Historical (pre-SpaceX): Ariane 5 GTO: $200M/launch ($10,000/kg). Atlas V GTO: $225M. Delta IV Heavy: $350M. SpaceX Falcon 9 (expendable): $62M/launch ($2,700/kg to LEO, 2015). Falcon 9 reused: $50M (2018), reaching $30M (2023 estimates, no public price list). Falcon Heavy: $97M expendable. Starship (target): $10M/launch or less at maturity — if achievable, transforms economics. New Glenn (Blue Origin): ~$70M. Vulcan Centaur (ULA): ~$100M. Electron (Rocket Lab): $7.5M (300 kg). Cost per kg to LEO trends: 2000: $10,000-20,000/kg; 2015: $2,700/kg (Falcon 9); 2023: $1,500/kg (estimated Falcon 9 reused); Starship target: $100/kg. Key insight: launch cost reduction follows learning curve (Wright's law). Each doubling of flights → 20-30% cost reduction. SpaceX flew 96 times in 2023, compressing learning curve."},

    # ─── DEEPENED: ORBITAL MECHANICS (20 chunks) ─────────────────────────────

    {"id": "orbital-transfers-001", "domain": "orbital_mechanics",
     "title": "Orbital Transfer Maneuvers",
     "source": "Vallado; Bate Mueller White, Fundamentals of Astrodynamics",
     "text": "Orbital transfers change a satellite's orbit using propulsive maneuvers. Hohmann transfer (minimum energy): two-impulse transfer between coplanar circular orbits. Δv1 = sqrt(μ/r1) × (sqrt(2r2/(r1+r2)) - 1) at perigee. Δv2 = sqrt(μ/r2) × (1 - sqrt(2r1/(r1+r2))) at apogee. LEO to GTO: Δv ≈ 2,400 m/s. GTO to GEO: Δv ≈ 1,500 m/s. Total: ~3,900 m/s. Plane change: expensive — Δv = 2v×sin(Δi/2). 28.5° plane change at LEO (7,500 m/s): 3,850 m/s. Combine plane change with Hohmann at apogee (higher altitude = slower speed = cheaper plane change). Bielliptic transfer: three-impulse, cheaper than Hohmann for large orbit changes (r2/r1 > 11.94). Continuous thrust (low-thrust): Δv ≈ Δv_Hohmann but takes months. Optimal for electric propulsion. Gravity assist: flyby a planet/moon to gain Δv without propellant cost (Voyager's grand tour, Cassini Venus-Earth-Earth-Jupiter)."},

    {"id": "orbital-formation-001", "domain": "orbital_mechanics",
     "title": "Formation Flying Dynamics",
     "source": "Clohessy & Wiltshire 1960; Gaias & D'Amico",
     "text": "Formation flying maintains two or more satellites in a controlled relative configuration. Clohessy-Wiltshire (CW) equations describe relative motion in a rotating reference frame (LVLH: local vertical, local horizontal): ẍ - 2nẏ - 3n²x = 0, ÿ + 2nẋ = 0, z̈ + n²z = 0. where n = mean motion, x = radial, y = along-track, z = cross-track. Natural relative motion (no thrust): in-plane motion follows ellipse (1:2 ratio radial:along-track). Drift-free formations require specific initial conditions. J2-invariant formations: design relative orbital elements to cancel J2 differential effects. Applications: distributed aperture (GRACE gravity mission: 200 km separation, measures distance to μm), synthetic aperture (TanDEM-X: 150-500 m separation for global DEM), distributed sensing (Cluster mission 4 spacecraft for magnetosphere). Station-keeping: periodic maneuvers to correct perturbation-induced drift. GRACE-FO (Follow-On): uses laser ranging interferometer (nanometer measurement precision) between 220 km separated spacecraft."},

    {"id": "orbital-rendezvous-001", "domain": "orbital_mechanics",
     "title": "Orbital Rendezvous and Proximity Operations",
     "source": "Fehse, Automated Rendezvous and Docking; ATV documentation",
     "text": "Rendezvous brings a chaser spacecraft to the vicinity of a target. Phases: phasing orbit (adjust period for catch-up), far-range approach (hopping maneuvers using CW equations), close approach (typically 0-200 m, laser ranging), docking/capture. ΔV for LEO rendezvous: phasing 10-50 m/s, proximity operations 5-15 m/s. Approach trajectory design: V-bar approach (along velocity vector of target) — natural drift in CW frame, safe (recede if no thrust). R-bar approach (along radial, toward Earth) — requires active braking, shorter path. Sensor suite: VHF for far-range, radar (lidar) for mid-range, camera for close approach. ATV (ESA Automated Transfer Vehicle): demonstrated autonomous docking to ISS. GPS relative navigation + telegoniometer for final approach. SpaceX Crew Dragon: autonomous docking, NASA guidance. Chinese Shenzhou/Tianzhou: autonomous docking to Tiangong. Failure mode: target orbit avoidance corridor — abort into trajectory that diverges from target without additional thrust."},

    {"id": "orbital-deorbit-001", "domain": "orbital_mechanics",
     "title": "Deorbit Strategies and Reentry",
     "source": "IADC; NASA 8719.14A; ESA debris mitigation standards",
     "text": "Post-mission disposal requires deorbit to comply with IADC 25-year rule (atmospheric reentry within 25 years). Strategies: (1) Natural decay: LEO below 600 km decays naturally within decades; below 400 km within years. (2) Propulsive deorbit: perigee lowered to 200-300 km for rapid decay (days-weeks). ΔV ≈ 150-200 m/s for satellite at 500 km. (3) Drag augmentation: deploy drag sail or balloon to increase area/mass ratio, accelerate decay. Example: InflateSail, Gossamer-1, DragEN. Passivation: vent all stored energy (propellant, battery, pressurized vessels) before deorbit to prevent explosion. Atmospheric reentry: heating begins at ~120 km altitude (Mach ~20). Demise altitude: most aluminum components melt at 2-3 km altitude, don't reach ground. Titanium, stainless steel, carbon composite may survive. Ground casualty area (Ac) requirement: < 8 m² for uncontrolled reentry (probability <1 in 10,000). Controlled reentry: guidance to impact in ocean (e.g., South Pacific Ocean Point Nemo — remote area for ISS disposal planned)."},

    # ─── DEEPENED: SPACE ENVIRONMENT (10 chunks) ──────────────────────────────

    {"id": "space-env-radiation-001", "domain": "space_environment",
     "title": "Van Allen Radiation Belts",
     "source": "NASA Van Allen Probes; Spence et al.; ECSS-E-ST-10-04C",
     "text": "The Van Allen belts are toroidal regions of trapped energetic particles in Earth's magnetosphere. Inner belt (1,000-6,000 km): dominated by protons (10-100 MeV), electrons. Source: cosmic ray albedo neutron decay (CRAND), solar protons. Very stable. Outer belt (13,000-40,000 km): electrons (0.1-10 MeV), variable with geomagnetic activity. Slot region (6,000-13,000 km): relatively empty, except during storms when electron injection occurs. South Atlantic Anomaly (SAA): weaker magnetic field region over South Atlantic, inner belt dips to lower altitudes (~200 km), causes enhanced radiation for LEO satellites passing through. ISS crew receives extra dose during SAA crossings. Radiation effects on electronics: total ionizing dose (TID), displacement damage (DD, lattice displacement by high-energy protons/neutrons), single event effects (SEE) from heavy ions/protons. Space-qualified components tested to 100 krad TID. Shielding: aluminum 3-5 mm reduces TID significantly; diminishing returns beyond 10 mm."},

    {"id": "space-env-spe-001", "domain": "space_environment",
     "title": "Solar Particle Events and Space Weather Impacts",
     "source": "NOAA SWPC; ESA space weather documentation; NASA CCMC",
     "text": "Solar Particle Events (SPEs) or proton events occur when flares and CMEs accelerate protons to high energies. Ground Level Enhancements (GLE): most energetic events, protons >450 MeV reach ground level, detected by neutron monitors. >170 GLEs since 1942. Energetic Storm Particles (ESP): associated with CME shocks, 1-100 MeV. SPE effects: (1) Increased radiation dose to astronauts — August 1972 event between Apollo 16 and 17 would have been lethal to unshielded crew; (2) Enhanced proton flux causes SEEs in spacecraft electronics; (3) Enhanced ionization in polar cap (polar cap absorption, PCA) blocks HF radio for days; (4) Increased drag for LEO satellites. Warning time: protons (v~0.9c) arrive within 20-30 minutes after flare detection; CME takes 1-4 days. NOAA SWPC issues S-scale (Solar radiation storm scale) S1-S5. S5: proton flux >10^5 particles/cm²/s at >10 MeV. October 2003 'Halloween storms': S4 event, caused satellite anomalies."},

    # ─── DEEPENED: SPACECRAFT OPERATIONS (10 chunks) ─────────────────────────

    {"id": "sc-ops-thermal-001", "domain": "spacecraft_operations",
     "title": "Spacecraft Thermal Control",
     "source": "Gilmore, Spacecraft Thermal Control Handbook; ECSS-E-ST-31",
     "text": "Spacecraft thermal control maintains components within operating temperature ranges (electronics: -20°C to +50°C; batteries: 0°C to +40°C; propellant: above freezing). Passive thermal control: Multi-Layer Insulation (MLI): alternating aluminized mylar layers, reduces effective emittance to 0.01-0.03. Thermal control surfaces: radiators (εIR=0.85-0.9, αsolar=0.1-0.2), solar absorbers (αsolar=0.9-0.95, εIR=0.5-0.9), optical solar reflectors (OSR, αsolar=0.1, εIR=0.8). Thermal coatings: white paint (S13G: α=0.21, ε=0.87), black Kapton (α=0.93, ε=0.93). Active thermal control: heaters (resistance wire, 5-50 W), heat pipes (loop heat pipes, variable conductance heat pipes), thermoelectric coolers (Peltier). Radiator sizing: Q_reject = ε×σ×A×T^4. For 100 W waste heat at 50°C (323 K): A = 100/(0.87×5.67×10^-8×323^4) = 0.37 m². Heat sources: electronics dissipation, battery charging, attitude control torques. Eclipse/sunlight cycling: temperature swings ±80°C typical for LEO (worst case for thermal fatigue)."},

    {"id": "sc-ops-adcs-001", "domain": "spacecraft_operations",
     "title": "Attitude Determination and Control Systems",
     "source": "Markley & Crassidis, Fundamentals of Spacecraft Attitude Determination; Wertz SMAD",
     "text": "ADCS maintains spacecraft orientation and stability. Attitude determination sensors: Sun sensors (coarse: ±2°, fine: ±0.03°), star trackers (±3-30 arcsec, most accurate), magnetometers (±1° in LEO, low cost), gyroscopes (ring laser gyro: <0.001°/hr drift, MEMS gyro: <5°/hr), GPS attitude (dual antenna: ±0.5°). Attitude control actuators: reaction wheels (0.01-0.1 Nm torque, require desaturation), magnetorquers (use Earth's magnetic field, no fuel, slow), thrusters (1-200 N, precise, use propellant), control moment gyroscopes (CMG, high torque for large satellites). Control laws: PD controller (proportional-derivative on error), quaternion feedback, LQR (Linear Quadratic Regulator). Pointing modes: nadir-pointing (sensor toward Earth), Sun-pointing (solar arrays toward Sun), inertially fixed (telescope), target-tracking (imaging). Pointing accuracy: GeoEye-1: 0.0009° (3.2 arcsec). Attitude knowledge: separate from control accuracy. ESA Gaia star catalog reference: determines attitude knowledge to 7 μarcsec."},

    # ─── DEEPENED: STANDARDS AND PROTOCOLS (10 chunks) ───────────────────────

    {"id": "standards-cyber-001", "domain": "standards_protocols",
     "title": "Satellite Cybersecurity Standards",
     "source": "NIST SP 800-82; CISA space systems guidance; ESA ESCC",
     "text": "Satellite cybersecurity has emerged as critical domain after 2022 Viasat cyberattack (KA-SAT) disrupted Ukraine communications at invasion start. Key threats: command injection (unauthorized commands), telemetry spoofing, ground station compromise, supply chain, jamming/spoofing. NIST SP 800-82 (Industrial Control Systems Security): applied to satellite ground segments. CISA Space Systems Critical Infrastructure guidance (2023): identifies space systems as critical infrastructure, outlines 6 security principles. ESA ESCC (European Space Components Coordination): hardware security requirements. NIST SP 800-207 (Zero Trust Architecture): applicable to satellite ground networks. Cryptographic requirements: AES-256 for data at rest, TLS 1.3 for ground segment communications, authenticated command encryption. US military (MILSATCOM): NSA Type 1 encryption for classified links. Commercial: growing adoption of authenticated command uplinking to prevent unauthorized commands. Jamming/spoofing threats: GPS spoofing (maritime incidents), uplink jamming (requires directional antennas), crosslink security. Key lesson from Viasat: ground segment security as important as space segment."},

    {"id": "standards-frequency-001", "domain": "standards_protocols",
     "title": "Frequency Coordination and ITU Process",
     "source": "ITU Radio Regulations 2020; FCC licensing; OFCOM",
     "text": "International frequency coordination prevents radio interference between satellites. ITU process: (1) Advance Publication (API): submit frequency filing at least 2 years before launch. Establishes priority date. (2) Coordination: bilateral coordination with affected administrations. (3) Notification: formal notification after coordination complete. ITU Master Register: permanent record of coordinated frequencies. Non-geostationary (NGSO) coordination: complex because NGSO satellites move relative to GEO arc. Equivalent Power Flux Density (EPFD) limits: protect GEO systems from NGSO interference. Starlink EPFD compliance: major coordination challenge with existing GEO operators. Spectrum fees: most countries charge annual fees for spectrum use. FCC licensing: US commercial satellites licensed by FCC under Part 25. License includes orbital parameters, frequency, power, coordination conditions. License transfer: allowed (enables secondary market for orbital slots). ITU coordination disputes: 2019 SpaceX-Amazon (Kuiper) dispute; historical South Korea vs. Tongasat filing dispute."},

    # ─── DEEPENED: ADDITIONAL AREAS (30 chunks) ──────────────────────────────

    {"id": "gnss-architecture-001", "domain": "orbital_mechanics",
     "title": "GNSS Constellation Architecture",
     "source": "GPS SPS Performance Standard; Galileo OS SIS ICD",
     "text": "Global Navigation Satellite Systems (GNSS) enable positioning, navigation, timing. GPS (USA): 31 operational satellites, MEO at 20,200 km, 6 orbital planes, 55° inclination, 12-hour period. Broadcasts L1 (1575.42 MHz), L2 (1227.60 MHz), L5 (1176.45 MHz). Civil accuracy: 2-4 m 95% global. GLONASS (Russia): 24 satellites, MEO at 19,100 km, 3 planes, 64.8° inclination. FDMA (frequency division) vs GPS CDMA. Galileo (EU): 30 satellites (24 operational + 6 spare), MEO at 23,222 km, 3 planes, 56° inclination. Open service 4 frequencies. First GNSS to guarantee service (OS performance guarantee). BeiDou-3 (China): 30 MEO + 3 GEO + 3 IGSO (inclined geosynchronous). Global service from 2020. NavIC (India): regional, 7 satellites (GEO + IGSO). QZSS (Japan): regional, 4 satellites. Multi-constellation receivers: use all systems simultaneously for better coverage, accuracy, redundancy. 30-35 satellites visible simultaneously for L1 multi-constellation receiver."},

    {"id": "debris-tracking-sensors-001", "domain": "debris_mitigation",
     "title": "Space Surveillance Network Sensors",
     "source": "US Space Command SSN documentation; 18th SpCS fact sheets",
     "text": "US Space Surveillance Network (SSN) consists of ~30 radar and optical sensors globally. Mechanical radars: Eglin FPS-85 (Florida): UHF phased array, 22 MW peak power. Primary LEO sensor. HAVE STARE (former Haystack radar update): L-band, precision tracking. UEWR (Upgraded Early Warning Radar) sites: Fylingdales (UK), Thule (Greenland), Beale (CA). PAVE PAWS radar: originally missile warning, now dual-use SSN. Mechanical-Electrical radars: Millstone Hill (MIT LL): narrowbeam for precision tracking. ALTAIR (Marshall Islands): VHF/UHF. Advanced phased array radars: Space Fence (Kwajalein): S-band, replaces previous VHF Fence. Can track 200,000+ objects > 2 cm in LEO. 24/7 automated tracking. Optical: GEODSS sites (Maui, New Mexico, Diego Garcia): 1 m telescopes for deep space objects. SST (Space Surveillance Telescope): 3.5 m, wide field. Data processing: Astrodynamics Support Workstation (ASW), AutoTrack for automated orbit determination from radar/optical observations. SSN covers ~27,000 cataloged objects (>10 cm LEO, >1 m GEO)."},

    {"id": "orbital-station-keeping-001", "domain": "orbital_mechanics",
     "title": "GEO Station-Keeping Strategy",
     "source": "Soop, Handbook of Geostationary Orbits; ESA ESOC GEO operations",
     "text": "Geostationary satellites must perform station-keeping maneuvers to maintain assigned orbital slot. Perturbations: (1) North-South (N-S): lunar/solar gravitational pull causes inclination growth at ~0.75°/year. Requires 50 m/s/year ΔV for N-S control. (2) East-West (E-W): triaxiality of Earth (4 stable/unstable equilibrium points at 75°E, 105°W, 161°E, 15°W), SRP. Requires 2-5 m/s/year ΔV. Combined annual ΔV: 50-55 m/s. For 15-year life: ~750 m/s. N-S station-keeping: two symmetric maneuvers per orbit (every 24 hours), tangential impulses to correct inclination. Inclination-inclined GEO (IGSO): some operators allow inclination growth, trading N-S fuel for extended life. Users need tracking antennas instead of fixed dishes. E-W station-keeping: stationkeep at longitude ±0.1°. Maneuver frequency: 1-4 maneuvers per month depending on longitude. GEO box: Intelsat/SES maintain satellites within ±0.05° longitude, ±0.05° latitude of nominal slot."},

    {"id": "ssa-conjunction-history-001", "domain": "space_situational_awareness",
     "title": "Historical Conjunction Events and Near Misses",
     "source": "ESA Space Debris Office; NASA CARA records; public reporting",
     "text": "Key historical conjunction events shaping SSA practices: Iridium-33/Cosmos-2251 (Feb 10, 2009): first confirmed collision between catalogued satellites. 789 km altitude, 42° inclination. Generated 2,296 trackable debris pieces (2023 count still >600). No warning issued — insufficient tracking data at time. Fermi-Cosmos 1805 (Apr 2012): NASA Fermi spacecraft performed evasive maneuver to avoid defunct Soviet satellite. NASA calculated Pc=1/100 (extremely high) — among highest ever seen for operational satellite. ESA-Starlink 44235 (Sep 2019): ESA was forced to maneuver Aeolus because SpaceX failed to respond to coordination request. SpaceX was still using old manual system, not automated. Led to new coordination protocols. Chinese ASAT debris/ISS (multiple events 2021-2022): Fengyun-1C debris (from 2007 test) caused multiple ISS maneuvers. Chinese space station also maneuvered. Starlink-Oneweb maneuver (2021): Starlink maneuvered 3 km away, resulting in OneWeb satellite performing own avoidance. Key policy lessons: automated conjunction screening mandatory at scale; shared responsibility unclear when both satellites active."},

    {"id": "mission-nrho-001", "domain": "mission_planning",
     "title": "Near-Rectilinear Halo Orbit and Lunar Gateway",
     "source": "NASA Gateway documentation; CAPSTONE mission report",
     "text": "Near-Rectilinear Halo Orbit (NRHO) is selected for NASA's Lunar Gateway station. NRHO characteristics: highly elliptical orbit around Moon, near L2 Lagrange point. Period: ~6.5 days. Periselene: ~1,500 km (southern hemisphere, closest approach). Aposelene: ~70,000 km. Stability: naturally stable over decades without large station-keeping (< 10 m/s/year). Access: multiple transfer trajectories from lunar orbit and Earth. Landing access: direct descent capability to south polar region (Artemis target). Advantages over low lunar orbit (LLO): lower ΔV for sustainability, solar power continuous (no eclipse), communication with Earth reliable. CAPSTONE (Cislunar Autonomous Positioning System Technology Operations and Navigation Experiment, 2022): 12U CubeSat, first spacecraft in NRHO. Demonstrated navigation autonomy (crosslink with LRO for ranging). Operated 1+ year. Gateway elements: PPE (Power and Propulsion Element, MaxarTech), HALO (Habitation and Logistics Outpost, Northrop Grumman). First elements planned 2025-2026."},

    {"id": "eo-sentinel-5p-001", "domain": "earth_observation",
     "title": "Atmospheric Monitoring from Space",
     "source": "Sentinel-5P TROPOMI documentation; MOPITT; OMI",
     "text": "Atmospheric composition satellites measure trace gases and aerosols from space. Sentinel-5P (2017): TROPOMI instrument, 3.5×5.5 km resolution (upgraded to 3.5×3.5 km in 2021). Measures: NO2 (nitrogen dioxide, air quality), SO2 (sulfur dioxide, volcanic, industrial), CO (carbon monoxide, fires), O3 (ozone, UV index), CH4 (methane, climate, oil/gas leaks), HCHO (formaldehyde, VOC proxy), aerosol. Daily global coverage. Applications: air quality monitoring (EU regulatory compliance), volcanic ash hazard, oil/gas methane leak detection (environmental regulation). MOPITT (TERRA): CO profile. OMI (AURA): O3, NO2, UV. SCIAMACHY (ENVISAT, 2002-2012): pioneered multi-gas atmospheric column measurements. GHGSat: commercial methane satellite (10 m resolution, enables individual facility monitoring). Tanager-1 (Planet, 2024): hyperspectral, 30 m resolution methane detection. Carbon Mapper: planned coalition of methane/CO2 satellites. Regulation: EU Corporate Sustainability Reporting Directive will require satellite-based emission verification for large companies."},

    {"id": "comms-delays-tcp-001", "domain": "communications",
     "title": "TCP Performance over Satellite Links",
     "source": "CCSDS 714.0-B-2; RFC 2488; Hughes Network Systems",
     "text": "TCP (Transmission Control Protocol) performs poorly over high-latency satellite links due to its slow-start and congestion avoidance mechanisms. Problem: TCP window size limits throughput. Throughput = WindowSize / RTT. For GEO (RTT=600 ms), maximum window size 64 KB: throughput = 64×1024×8 / 0.6 = 873 kbps — far below physical link capacity. Solutions: (1) Large window sizes (RFC 1323): TCP extensions allow window sizes up to 1 GB. (2) Performance Enhancing Proxies (PEPs): terminate TCP at ground station, use UDP or custom protocol over satellite, re-TCP to internet. Hubbard-Westell approach, common in VSAT systems. (3) TCP BBR (Bottleneck Bandwidth and Round-trip propagation time): Google's TCP variant, better for high BDP links. (4) QUIC (IETF): UDP-based replacement for TCP, connection establishment faster, better loss recovery. (5) CCSDS Bundle Protocol (CCSDS 734.2): delay-tolerant networking for deep space. Applicable where RTT is minutes to hours."},

    {"id": "orbital-coord-001", "domain": "orbital_mechanics",
     "title": "Coordinate Systems in Space Operations",
     "source": "Vallado, Fundamentals of Astrodynamics 4th ed.; IAU SOFA",
     "text": "Multiple coordinate systems are used in satellite operations. Earth-Centered Inertial (ECI/GCRF): origin at Earth's center, X toward vernal equinox (J2000.0), Z toward celestial north pole. Used for orbit propagation. Earth-Centered Earth-Fixed (ECEF/ITRF): rotates with Earth, X toward Greenwich meridian. Used for ground station positions, mapping. Transformation ECEF→ECI: R3(-GAST) rotation by Greenwich Apparent Sidereal Time. Topocentric Horizon: origin at ground station, local horizontal plane. Azimuth-Elevation-Range for tracking. RTN (Radial-Transverse-Normal) / LVLH: satellite-centered frame, R radial (toward Earth), T transverse (velocity direction), N normal to orbit plane. Used for covariance representation in CDMs and formation flying. Body-fixed frame: aligned with satellite structure. Used for attitude determination and control. ECI vs ECEF accuracy: IAU2006/2000A precession-nutation model used for high accuracy (sub-centimeter). IERS publishes Earth orientation parameters (EOP) daily: UT1-UTC, polar motion (x,y)."},

    {"id": "propulsion-bipropellant-001", "domain": "propulsion",
     "title": "Bipropellant Satellite Propulsion Systems",
     "source": "Sutton; Larson & Wertz SMAD; satellite documentation",
     "text": "Bipropellant propulsion systems use separate fuel and oxidizer, providing higher Isp than monopropellant. Common combinations: MMH/N2O4 (mono-methyl hydrazine / nitrogen tetroxide): Isp 310-340 s, storable, hypergolic (auto-ignites on contact), space-proven 50+ years. Standard for GEO station-keeping, orbit insertion. Hydrazine/N2O4: less common. MON-3 (mixed oxides of nitrogen + 3% NO): less corrosive than pure N2O4. Engine sizes: 5-500 N thrusters for spacecraft. Aerojet R-4D (490 N): MMH/N2O4, 311 s Isp, ISS service vehicles. Aerojet R-42: 890 N, upper stage. Pressurization system: blow-down (decreasing pressure as propellant consumed) vs regulated (pressure regulator maintains constant tank pressure). Regulated provides constant thrust but adds component mass. Feed system: propellant isolation valves, latch valves, filter, pressure transducers. Propellant budget: satellite carries 40-50% of launch mass as bipropellant for 15-year life (GEO)."},

    {"id": "eo-thermal-ir-001", "domain": "earth_observation",
     "title": "Thermal Infrared Remote Sensing",
     "source": "ASTER documentation; ECOSTRESS; Landsat TIRS",
     "text": "Thermal infrared (TIR) remote sensing measures emitted radiation from Earth's surface (8-14 μm). Stefan-Boltzmann law: M = ε×σ×T⁴. At 300 K Earth surface: peak emission at ~9.7 μm. Applications: land surface temperature (LST) mapping, sea surface temperature (SST), urban heat island mapping, fire detection, volcano monitoring, soil moisture inference, evapotranspiration (ET) estimation. Sensors: Landsat 8/9 TIRS: 2 TIR bands (10.6, 11.5 μm), 100 m resolution. MODIS: 7 TIR bands, 1 km. ASTER (Terra): 5 TIR bands, 90 m. ECOSTRESS (ISS, 2018): 70 m resolution, 5 TIR bands, LST/ET global. VIIRS: 375 m, global daily. Atmospheric correction: atmosphere absorbs and emits in TIR — split window algorithm uses two TIR bands to correct (Landsat TIRS split window). Temperature accuracy: 0.5-1 K with good calibration. Night-time LST: enables anthropogenic heat detection without solar contamination. Fire radiative power: MODIS fire product detects active fire pixels, estimates energy release rate."},

    {"id": "comms-nbiot-sat-001", "domain": "communications",
     "title": "NB-IoT and Direct-to-Device Satellite Connectivity",
     "source": "3GPP Release 17; AST SpaceMobile; Lynk Global; SpaceX D2D",
     "text": "Direct-to-device (D2D) satellite connectivity allows unmodified smartphones to connect to LEO satellites. Technical approach: modified NB-IoT (Narrowband IoT) or 5G NR NTN (Non-Terrestrial Networks) protocol from 3GPP Release 17. Challenges: Doppler shift (up to 400 kHz at VHF, compensated by satellite pre-compensation), time alignment (range changes rapidly requiring timing advance adjustment), multipath (single satellite, no multipath like cellular), weak signal (satellite much farther than ground tower). AST SpaceMobile: very large satellites (22 m² aperture on BlueBird), partner with AT&T/Verizon/Rakuten. BlueWalker 3 prototype (2022): successfully demonstrated 2-way voice call on unmodified iPhone. Lynk Global: 1U CubeSat-based approach, text messaging initially. SpaceX Starlink D2D (2024): T-Mobile partnership, texts initially, voice/data planned. Globalstar/Apple Emergency SOS: simplified 1-way messaging. Market: 3B+ people in cellular coverage gaps (oceans, rural areas, developing world). Revenue potential: $20-50B/year global addressable market."},

    {"id": "mission-lunar-nav-001", "domain": "mission_planning",
     "title": "Lunar Navigation and Communications Architecture",
     "source": "NASA LunaNet; ESA Moonlight; CAPSTONE documentation",
     "text": "Lunar navigation requires infrastructure beyond Earth GPS. Current limitations: GPS signal too weak at lunar distance for standard navigation (signal -7 dB relative to threshold). Solutions in development: NASA LunaNet: standards-based architecture for lunar communication and navigation services. Interoperability with ESA, JAXA. Services: relay communications, positioning, timing. Lunar surface navigation: landing systems (terrain-relative navigation), surface rovers (visual odometry, radar). ESA Moonlight: constellation of 2-3 satellites in lunar orbit providing continuous navigation/comms over lunar south pole. KPLO/Danuri (Korea, 2022): first lunar orbiter with GNSS receiver above GPS constellation, receiving GPS side-lobe signals — demonstrated 1-3 km accuracy at lunar distance. CAPSTONE (NRHO demonstration, 2022): tested crosslink navigation with LRO (Lunar Reconnaissance Orbiter) — Autonomous Navigation System (ANS). Future: LNSSat (Lunar Navigation Satellite System) proposed by multiple agencies. Artemis Base Camp will need continuous comms/nav from multiple access points, justifying dedicated infrastructure."},

    {"id": "commercial-on-orbit-servicing-001", "domain": "commercial_space",
     "title": "On-Orbit Servicing Market",
     "source": "Northrop Grumman MEV; Astroscale; Space Logistics documentation",
     "text": "On-orbit servicing (OOS) enables life extension, repair, and upgrade of spacecraft in orbit. Northrop Grumman Mission Extension Vehicle (MEV): first commercial OOS. MEV-1 (2020): docked to Intelsat 901 at GEO, extended life 5 years. MEV-2 (2021): docked to Intelsat 10-02. Uses existing GEO satellite apogee engine for docking. $100M per mission. Mission Extension Pod (MEP): smaller, separates from MEV, attaches to customer satellite, provides propulsion. Market size: ~300 GEO satellites approaching end-of-life in next decade. At $50-100M/mission: $15-30B market. Astroscale ELSA (End-of-Life Services by Astroscale): ELSA-d demonstrated magnetic docking/release of debris simulator (2021). ELSA-m: commercial debris removal service. Docking challenge: most satellites not designed for capture — no standard grasping interface. CONFERS (Consortium for Execution of Rendezvous and Servicing Operations): Northrop + industry developing docking standards. NASA OSAM-1 (On-orbit Servicing, Assembly, Manufacturing): robotic refueling demonstration planned. In-space Manufacturing: Redwire Industries 3D printing metal in space (ISS experiments), Varda Space Industries in-orbit pharmaceutical manufacturing."},

    {"id": "debris-leo-sustainability-001", "domain": "debris_mitigation",
     "title": "LEO Sustainability Frameworks",
     "source": "UN COPUOS; ITU; FCC; ESA sustainability standards",
     "text": "Multiple international frameworks address LEO sustainability: IADC Space Debris Mitigation Guidelines (2002, updated 2007): 25-year deorbit rule, passivation, protected zones. Non-binding but widely adopted. ISO 24113 (2019): legal standard incorporating IADC guidelines. UN COPUOS Guidelines (2019): 21 guidelines for long-term sustainability (LTS) of outer space. Consensus-based, voluntary, but diplomatically significant. National regulations: FCC 5-year deorbit rule (2022): US-licensed LEO satellites must deorbit within 5 years of end-of-mission. More stringent than IADC 25-year rule. Applies to SpaceX, Amazon, others with US FCC licenses. UK Space Agency: similar 5-year rule for UK-licensed satellites. ESA Zero Debris Charter (2023): ESA commits to generating zero debris by 2030, requiring all ESA-prime missions to be compliant. Sustainability metrics: (1) Orbital carrying capacity (number of satellites a shell can sustain without unacceptable collision risk increase); (2) Satellite density vs Kessler threshold; (3) Post-mission disposal compliance rate (currently ~70% globally). Industry initiatives: Space Sustainability Rating (SSR): voluntary rating system developed by ESA, MIT Media Lab, and others — grades sustainability practices of satellite operators."},

    {"id": "propulsion-thruster-catalog-001", "domain": "propulsion",
     "title": "Spacecraft Thruster Catalog",
     "source": "Aerojet; ArianeGroup; Bradford ECAPS; Moog; Northrop Grumman",
     "text": "Common spacecraft thrusters by application: Attitude control (1-5 N): Aerojet MR-103H hydrazine monoprop (Isp 220 s), Moog DST-11 hydrazine (0.9-5 N, Isp 229 s), Northrop CHAMPS-R (1N biprop). Station-keeping small: Aerojet MR-111 hydrazine (1 N, 220 s), Bradford HPGP ECAPS 1N (241 s, LMP-103S). Medium (22-490 N): Aerojet R-4D-11 biprop (490 N, MMH/MON-3, 311 s) — used on Apollo CSM and widely on GEO satellites. Moog 445N biprop: Deep Space 1, Mars Reconnaissance Orbiter. Large apogee motor (440-500 N): Aerojet R-4D-15, ArianeGroup S400. Used for GTO-GEO insertion. Very large (≥1 kN): Moog 445N thruster cluster, ArianeGroup Aestus (29 kN, ATV apogee). Monoprop choice: hydrazine vs. green (AF-M315E, LMP-103S). Biprop advantages: 30-40% more Isp, more energetic; disadvantage: two propellant systems, more complexity. Cold gas thrusters: nitrogen (Isp ~70 s), for very precise/low-thrust applications (formation flying, attitude on cubesats)."},

    {"id": "eo-precipitation-001", "domain": "earth_observation",
     "title": "Precipitation and Hydrology from Space",
     "source": "GPM Core Observatory; TRMM documentation; ESA SWOT",
     "text": "Satellite measurement of precipitation enables global weather monitoring and flood forecasting. TRMM (Tropical Rainfall Measuring Mission, 1997-2015): first spaceborne precipitation radar (Ku-band, 13.8 GHz), TRMM Microwave Imager (TMI). Validated satellite rain rates against ground radar. GPM (Global Precipitation Measurement, 2014): successor to TRMM. Core Observatory: dual-frequency precipitation radar (Ku+Ka band). 65° inclination → global coverage including mid-latitudes (vs TRMM 35°). GMI (GPM Microwave Imager): 13 channels, 10-183 GHz. Global precipitation products (IMERG) combine GPM with constellation of radiometers at 0.1°/30-min. Applications: flood forecasting (30-minute precipitation accumulation critical), agricultural drought monitoring, hurricane track and intensity. SWOT (Surface Water and Ocean Topography, 2022): measures lake/river water levels, ocean surface height to 2 cm precision. First global lake inventory. Snow depth: AMSR-E/AMSR2 passive microwave."},

    {"id": "commercial-analytics-001", "domain": "commercial_space",
     "title": "EO Analytics and AI Pipeline",
     "source": "Planet Labs; Maxar; Orbital Insight; Palantir documentation",
     "text": "Earth Observation analytics pipelines transform raw imagery into intelligence products using AI. Data pipeline: raw sensor data → atmospheric correction → orthorectification → cloud masking → object detection/change detection → derivative products → API delivery. Computer vision models: YOLO (You Only Look Once): real-time object detection for vessel detection, vehicle counting. U-Net: semantic segmentation for land cover classification, building footprints, crop type mapping. Siamese networks: change detection between image pairs. Foundation models: SAM (Segment Anything Model, Meta): applied to EO imagery for zero-shot segmentation. CLIP: multi-modal, matches image content to text queries. Scale AI, CVAT: annotation platforms for training data labeling. Commercial applications: Orbital Insight: retail parking lot counting for economic intelligence (before quarterly earnings), port vessel monitoring. Maxar: building damage assessment in conflict zones (Ukraine), used by UN OCHA. Planet: crop failure prediction, deforestation alerts (Amazon real-time monitoring). SpaceKnow: satellite manufacturing intelligence (factory parking lots). Key metric: time from tasking to insight delivery — < 1 hour for premium services."},
]

# Statistics check
domains = {}
for chunk in CORPUS_V5:
    d = chunk["domain"]
    domains[d] = domains.get(d, 0) + 1

if __name__ == "__main__":
    print(f"Total new chunks: {len(CORPUS_V5)}")
    print("By domain:")
    for domain, count in sorted(domains.items()):
        print(f"  {domain}: {count}")
